version: '3'
networks:
  my-bridge:
    external: true
services:
  nginx:
    build: ./nginx
    container_name: nginx
    hostname: nginx
    volumes:
      - ..:/usr/share/nginx/html:rw
    ports:
      - 8080:80
    networks:
      - my-bridge
    working_dir: /usr/share/nginx/html

  php:
      build: ./php
      container_name: php
      hostname: php
      volumes:
        - ../:/var/www/html:rw
        - ..:/usr/share/nginx/html:rw
      networks:
        - my-bridge
      working_dir: /usr/share/nginx/html
#      command:
#        - /bin/bash
#        - -c
#        - |
#        - mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

#  php7:
#      build: ./php7
#      container_name: php7
#      ports:
#        - "90001:9000"
#        - "5200:5200"
#        - "8001:8001"
#        - "8002:8002"
#        - "8003:8003"
#        - "8004:8004"
#        - "8011:8011"
#      links:
#        - "mysql:mysql"
#        - "redis:redis"
#        # - "ssdb:ssdb"
#      volumes:
#        - "~/Documents/docker/www:/docker/www"
#        - "~/Documents/docker/log:/docker/log"
#      environment:
#        TZ: "Asia/Shanghai"
#      working_dir: "/docker"
#      restart: "no"
#      cap_add:
#        - sys_ptrace



#  redis:
#    build: ./redis
#    container_name: redis
#    ports:
#      - "127.0.0.1:6379:6379"
#    working_dir: "/root"
#    restart: "no"

#   ssdb:
#     build: ./ssdb
#     container_name: ssdb
#     ports:
#       - "8888:8888"
#     working_dir: "/root"
#     restart: "no"
    
#  mysql:
#    container_name: mysql
#    image: mysql:5.7.23
#    command: --default-authentication-plugin=mysql_native_password
#    restart: "no"
#    ports:
#      - "127.0.0.1:33061:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: xy123456

#   postgres:
#     container_name: postgres
#     image: postgres:11.2
#     restart: "no"
#     ports:
#       - "127.0.0.1:5432:5432"
#     environment:
#       POSTGRES_PASSWORD: xy123456
  
#   grafana:
#     container_name: grafana
#     image: grafana/grafana:5.4.3
#     restart: "no"
#     ports:
#         - 127.0.0.1:3000:3000
#     environment:
#         - TZ=Asia/Shanghai
#         - GF_SECURITY_ADMIN_USER=root
#         - GF_SECURITY_ADMIN_PASSWORD=xy123456
#     volumes:
#       - "./runtime/grafana/data:/var/lib/grafana"
