version: '3'
services:
  es:
    build: elasticsearch-kibana
    container_name: es
    hostname: es
    restart: "no"
    ports:
      - "5601:5601"
      - "9200:9200"
    volumes:
      - ./elasticsearch-kibana/config:/home/elasticsearch/elasticsearch/config:rw
      - ./elasticsearch-kibana/data:/home/elasticsearch/elasticsearch/data:rw

  logstash:
    build: logstash
    container_name: log
    restart: "always"
    depends_on:
      - es
    links:
      - "es:es"
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
      - "/Users/jim/Workdata/yx_course/runtime/log/yx_course-2020-01-13.log:/yx_course.log:rw"
      - "/Users/jim/Workdata/yx_hsr_v5/runtime/log/yx_hsr_v5-2020-01-13.log:/yx_hsr_v5.log:rw"
      - "/Users/jim/Workdata/wwwlogs/dev-course-v3.classba.cn_nginx.log:/dev-course-v3.classba.cn_nginx.log:rw"
    environment:
      SLEEP_SECOND: 4
    tty: true
    #entrypoint: /entrypoint.sh -d es:9200 -c 'nohup /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/tcp.conf >/var/log/logstash.nohup.log 2>&1 &';